[project]
name = "flowcean"
version = "0.2.0"
description = "Automatic generation of models for cyber-physical systems."
readme = "README.md"
requires-python = ">=3.12,<4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = []
authors = [
    { name = "The AGenC Team", email = "agenc.team@tuhh.de" }
]

dependencies = [
    "docker>=7.1.0",
    "grpcio>=1.67.0",
    "joblib>=1.4.2",
    "lightning>=2.4.0",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-section-index>=0.3.9",
    "numpy>=1.26.4",
    "polars>=1.9.0",
    "protobuf>=5.28.2",
    "rosbags-dataframe>=0.10.0",
    "rosbags>=0.10.4",
    "ruamel-yaml>=0.18.6",
    "scikit-learn>=1.5.2",
    "scipy>=1.14.1",
    "torch>=2.5.0",
    "tqdm>=4.66.5",
]

[project.urls]
Documentation = "https://www3.tuhh.de/agenc/"
Issues = "https://github.com/flowcean/flowcean/issues"
Source = "https://github.com/flowcean/flowcean"

[tool.uv]
dev-dependencies = [
    "deptry>=0.20.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-material>=9.5.41",
    "mkdocs>=1.6.1",
    "mkdocstrings[python]>=0.26.2",
    "pre-commit>=4.0.1",
    "pyright>=1.1.385",
    "pytest-cov>=5.0.0",
    "pytest>=8.3.3",
    "ruff>=0.7.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.pyright]
ignore = [
    "src/flowcean/learners/grpc/_generated/*",
]
pythonVersion = "3.12"
strict = [
  "src/flowcean/core",
]

[tool.coverage.run]
source_pkgs = ["flowcean"]
omit = [
    "src/flowcean/learners/grpc/_generated/*",
]
branch = true
parallel = true

[tool.coverage.report]
skip_empty = true
exclude_also = [
    "pass",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]
