[project]
name = "automatic-lashing-platform"
version = "0.1.0"
requires-python = ">=3.10, <4.0"
dependencies = [
    "flowcean",
    "matplotlib",
    "graphviz",
]

[tool.pyright]
extends = "../../pyproject.toml"

[tool.uv.sources]
flowcean = { workspace = true }
